## NOTE KEEP SPACING BETWEEN CHUNKS
##
#--
#cloud-config
#--
users:
  - name:
    groups: sudo
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    ssh-authorized-keys:
#--
package_upgrade: true
#--
packages:
#--
write_files:
  - path:
    content: |
#--
runcmd:
  - 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu xenial/" | sudo tee -a /etc/apt/sources.list'
  - gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
  - gpg -a --export E084DAB9 | sudo apt-key add -
  - sudo add-apt-repository -y ppa:opencpu/opencpu-1.6
  - sudo apt-get update -y
  - sudo apt-get install -y r-base r-base-dev libssl-dev libcurl4-gnutls-dev libssh2-1-dev
  - sudo chmod +x /install_rstudio_ocpu.sh
  - sudo /install_rstudio_ocpu.sh
#--
power_state:
 mode: reboot
 message: Bye Bye
 timeout: 30
 condition: True
#--
