#cloud-config
users:
  - name:
    groups: sudo
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    ssh-authorized-keys:
package_upgrade: true
packages:
write_files:
  - path:
    content: |
runcmd:
  - 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu xenial/" | sudo tee -a /etc/apt/sources.list'
  - gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
  - gpg -a --export E084DAB9 | sudo apt-key add -
  - sudo add-apt-repository -y ppa:opencpu/opencpu-1.6
  - sudo apt-get update -y
  - sudo apt-get install -y r-base r-base-dev
  - sudo apt-get install -y libssl-dev libcurl4-gnutls-dev libssh2-1-dev
  - sudo chmod +x /silent-install-ocpu.sh
  - sudo /silent-install-ocpu.sh

